"""update_table_user

Revision ID: 4be82a1167aa
Revises: 68dc948d5d2b
Create Date: 2025-11-05 11:53:56.554533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be82a1167aa'
down_revision: Union[str, Sequence[str], None] = '68dc948d5d2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('is_new', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('accepted_privacy_policy', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'accepted_privacy_policy')
    op.drop_column('users', 'is_new')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
